In [24]:
import pandas as pd
IGC_df = pd.read_excel(r'C:\Users\jaff_\Documents\Dados Dissertação\Qualidade\portal_IGC_edicao2018 (1).xlsx')

In [25]:
IGC_df = IGC_df[['Código da IES', 'Alfa (Proporção de Graduação)', 'Beta (Proporção de Mestrado - Equivalente)', 'Gama (Proporção de Doutorandos – Equivalente)', 'IGC (Faixa)']]
display(IGC_df)

,Código da IES,Alfa (Proporção de Graduação),Beta (Proporção de Mestrado - Equivalente),Gama (Proporção de Doutorandos – Equivalente),IGC (Faixa)
0,651,NaN,0.0,0.0,SC
1,708,NaN,0.0,0.0,SC
2,1072,NaN,0.0,0.0,SC
3,1501,NaN,0.0,0.0,SC
4,1628,NaN,0.0,0.0,SC
...,...,...,...,...,...
2066,1609,1.0,0.0,0.0,1
2067,1938,1.0,0.0,0.0,1
2068,2726,1.0,0.0,0.0,1
2069,12268,1.0,0.0,0.0,1
2070,19252,1.0,0.0,0.0,1

In [31]:
IGC_df = IGC_df.rename(columns={'Código da IES':'CO_IES'})
IGC_df = IGC_df.rename(columns={'Alfa (Proporção de Graduação)':'Graduacao'})
IGC_df = IGC_df.rename(columns={'Beta (Proporção de Mestrado - Equivalente)':'Mestrado'})
IGC_df = IGC_df.rename(columns={'Gama (Proporção de Doutorandos – Equivalente)':'Doutorado'})
display(IGC_df)

      CO_IES  Graduacao  Mestrado  Doutorado IGC (Faixa)
0        651        NaN       0.0        0.0          SC
1        708        NaN       0.0        0.0          SC
2       1072        NaN       0.0        0.0          SC
3       1501        NaN       0.0        0.0          SC
4       1628        NaN       0.0        0.0          SC
...      ...        ...       ...        ...         ...
2066    1609        1.0       0.0        0.0           1
2067    1938        1.0       0.0        0.0           1
2068    2726        1.0       0.0        0.0           1
2069   12268        1.0       0.0        0.0           1
2070   19252        1.0       0.0        0.0           1

[2071 rows x 5 columns]

In [32]:
IGC_df.to_excel(r'C:\Users\jaff_\Google Drive\_Dissertação\Dados Dissertação\Python\IGC.xlsx')